In [1]:
import numpy as np

# 1.Tạo ma trận

#### a. Basic

In [13]:
#np.arange(start,stop,step)
mat = np.arange(0,100,5)
mat

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
#np.linspace(start,stop,quantity)
mat = np.linspace(5,100,20)
mat

In [15]:
#ndarray.reshape(row,col) 
#row*col phải bằng số lượng phần tử trong mảng ndarrayndarray
mat=mat.reshape(2,2,5)
mat

array([[[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]],

       [[50, 55, 60, 65, 70],
        [75, 80, 85, 90, 95]]])

#### b. Special

In [7]:
print("===========================")
print(f"Ma trận 0 :\n\n{np.zeros(9).reshape(3,3)}")
print("\n===========================")
print(f"Ma trận đường chéo :\n\n{np.ones(9).reshape(3,3)}")
print("\n===========================")
print(f"Ma trận ngãu nhiên :\n\n{np.empty(4).reshape(2,2)}")

Ma trận 0 :

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ma trận đường chéo :

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Ma trận ngãu nhiên :

[[0.00000000e+000 9.70190358e-312]
 [9.70190359e-312 9.70190358e-312]]


# 2.Các thông số của ma trận

#### a. Số lượng phần tử có trong ma trận và kiểu dữ liệu của các phần tử đớ

In [28]:
print(f"mat: \n{mat}\n============================================")
print(f"Số lượng phần tử có trong mảng: {mat.size}")
print(f"Kiểu dữ liệu của ma trận: {mat.dtype}")

mat: 
[[[ 0  5 10 15 20]
  [25 30 35 40 45]]

 [[50 55 60 65 70]
  [75 80 85 90 95]]]
Số lượng phần tử có trong mảng: 20
Kiểu dữ liệu của ma trận: int64


#### b. Số chiều của mảng

In [11]:
print(f"mat: \n{mat}")
print(f"\nSố chiều mảng có: {mat.ndim}")

mat: 
[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]

Số chiều mảng có: 2


#### c.  Kích thước hàng/cột của mảng

In [20]:
# Hàm trả về giá trị là mảng gồm kích thước theo các chiều 
# => số phân tử trong mảng kết quả là số chiều của ma trận và cũng có thể truy cập trực tiếp
print(f"mat: \n{mat}\n============================================")
print(f"Kích thước ma trận theo các chiều: {mat.shape}")
print(f"Kích thước ma trận theo chiều thứ nhất: {mat.shape[0]}")

mat: 
[[[ 0  5 10 15 20]
  [25 30 35 40 45]]

 [[50 55 60 65 70]
  [75 80 85 90 95]]]
Kích thước ma trận theo các chiều: (2, 2, 5)
Kích thước ma trận theo chiều thứ nhất: 2
